# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170616_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 6, 17, 7, 2, 50, 847160, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
